Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Style/EndOfLine:
  EnforcedStyle: lf
Style/AsciiComments:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/BlockComments:
  Enabled: false
Metrics/MethodLength:
  Max: 60
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Max: 50
Metrics/ClassLength:
  Max: 500
Metrics/PerceivedComplexity:
  Max: 12
Metrics/CyclomaticComplexity:
  Max: 10
Style/ClassVars:
  Enabled: false
Lint/DuplicateMethods:
  Enabled: false